# Generated by Django 4.2 on 2025-10-24 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessingSession',
            fields=[
                ('session_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('total_pages', models.IntegerField()),
                ('document_type', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('completed_pages', models.IntegerField(default=0)),
                ('failed_pages', models.IntegerField(default=0)),
                ('processing_page', models.IntegerField(blank=True, null=True)),
                ('documents', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('pages_info', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initializing', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batch_processing_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
