# Generated by Django 4.2 on 2025-10-24 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchprocessingsession',
            options={},
        ),
        migrations.AddField(
            model_name='batchprocessingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchprocessingsession',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='batchprocessingsession',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='batchprocessingsession',
            name='pages_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='batchprocessingsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batchprocessingsession',
            name='status',
            field=models.CharField(default='initializing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='batchprocessingsession',
            index=models.Index(fields=['status', 'started_at'], name='batch_proce_status_c7ac7e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchprocessingsession',
            index=models.Index(fields=['session_id'], name='batch_proce_session_1f54b7_idx'),
        ),
    ]
