# Generated by Django 4.2 on 2025-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_alter_batchprocessingsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocessingsession',
            name='pages_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
