# Generated by Django 4.2 on 2025-09-14 18:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Rebut', 'Rebut'), ('NPT', 'NPT'), ('Kosu', 'Kosu')], max_length=10)),
                ('json_url', models.URLField(blank=True, max_length=500, null=True)),
                ('excel_url', models.URLField(blank=True, max_length=500, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('retry_used', models.CharField(blank=True, max_length=255, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_user', models.BooleanField(default=False)),
                ('history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_fc21d0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_created_3c6eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['filename'], name='documents_filenam_64880e_idx'),
        ),
    ]
